sudo: required
dist: trusty

language: python
python:
    - "3.6"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libportmidi-dev libportaudio-dev libgl1-mesa-dev xvfb
 - pip3 install pygame
 - pip3 install pyopengl
 - pip3 install grpcio==1.4.0 #grpcio >= 1.6.0 has an issue with load balancing: https://github.com/grpc/grpc/issues/12506 and grpc >= 1.8.0 has another issue: https://github.com/grpc/grpc/issues/14088

#cache:
#    directories:
#    - $HOME/assimp

script: "./.travis.bash"

