sudo: required
dist: xenial

language: generic

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-opengl python-pygame libgl1-mesa-dev xvfb
 - sudo pip install grpcio

#cache:
#    directories:
#    - $HOME/assimp

script: "./.travis.bash"

