sudo: required
dist: trusty

language: generic

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python3 python3-pip python3-numpy libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libportmidi-dev libportaudio-dev libgl1-mesa-dev xvfb
 - sudo pip3 install six>=1.9
 - sudo pip3 install pygame
 - sudo pip3 install pyopengl
 - sudo pip3 install grpcio==1.4.0 #grpcio >= 1.6.0 has an issue with load balancing: https://github.com/grpc/grpc/issues/12506 and grpc >= 1.8.0 has another issue: https://github.com/grpc/grpc/issues/14088

#cache:
#    directories:
#    - $HOME/assimp

script: "./.travis.bash"

